# -*- coding: utf-8 -*-
"""python_jan batch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FGMfiwFtwHScA3uioAJeT5hEJiF4Gp_O
"""

#function
def add(num1,num2):
 print("The addition of two values are",(num1+num2),"the difference of two values are",(num1-num2))
add(2222,22222)

num=int(input("enter the range: "))
for a in range(1,num+1):
  print(a)
num1=("hi","hello","fawad","fafa","fanu","018")
for a in num1:
  print("the values in tuple are:",a)

for y in range(1,11):
  print("the values are",y)



#add 
num2=1
num3=2
num4=num2+num3
print(num4)

def x():
  for i in range(0,-8,-5):
    print("hello")
x()

if(2>6):
  print("the first number is greater")
elif (2=="2"):
  print("the second number is greater")
else:
  print("none")

def quiz():
  n=input()
  if n==("a"or"b"or"d"):
   print("you where lose")
  elif n=="c":
   print("you where won")
quiz()

def add1():
  num1=int(input("enter the first numbe"))
  num2=int(input("enter the second numbet"))
  print("the values are",(num1+num2))
add1()



def a(name):
  print("my favorite cartoon is",name)
a("tom")

a=8
for x in range(0,a):
  print(x)