# -*- coding: utf-8 -*-
"""python - jan batch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SCUhzNeuZaSjDBnTFO8qQ8X3bMJKvbCU
"""

#dictionary

mydic={
    "brand":"fujitsu",
    "colour":"red",
    "year of making":"2012",
    "price":"30000"
}
print(mydic)
#update
mydic["colour"]="black"
print(mydic)

mydic["model"]="500"
print(mydic)

del mydic["year of making"]
print(mydic)

#set     
myset={"data","data1",0,0,"task"}
print(myset)
for a in myset:
  print(a)
#add
myset.add("true")
print(myset)

print("hello world\nits me fafa ")

#function
def a():
  print("hello world\nits me fafa")
a()
a()
a()
a()
a()

def add(num1,num2):
  print("the addition of two values are",(num1+num2))
  add(465,777)

def add1():
  num1=input("enter the first number")
  num2=input("enter the second number")
  print("the values are",(num1+num2))
add1()